#!/usr/bin/env python3
"""Read a session out of `refined/`: format facts, not filtering policy.

    Input (read-only):  <resync_home>/refined/<session>.epoch*.jsonl

Every analysis script builds its own view straight from `refined/` — the whole
corpus parses in about a second, so there is no reason to share an intermediate
file, and sharing one cost us eight of the seventeen categories in
`INEFFICIENCIES.md`. `friction.py` was text-only, which served the exchange and
claim-pair views and silently blocked the action log, the request ledger and
claim provenance.

What is shared here is only what it costs real debugging to discover: how the
transcript is *shaped*. Each of these was a bug before it was a fact.

  * `isMeta` marks a platform-generated user-role line. One such line in
    session 0825c6b6 held 94,691 of the 96,984 characters stored as "your
    messages" — 97.6%.
  * An AskUserQuestion result is PROSE, not structure: `"Q"="A", "Q2"="A2"`.
    `events.jsonl` carries the parsed dict but only for 18 of the corpus's 31
    uses; the transcript has all 31.
  * A slash command arrives as a user-role line opening `<command-name>`, with
    its argument in `<command-args>`. `/ds` is the one worth recovering — the
    note says what the right answer was — and `-N` must be stripped exactly as
    `intercept.py` strips it or the same marker counts twice.
  * A denial's reason is `toolDenialKind`, and only `user-rejected` reflects a
    human decision. Of 132 denials, 73 are `permission-rule` (a static
    allowlist) and 30 are `automode-*` (the harness).
  * A compaction summary is a genuine user-role line that `isMeta` does not
    catch, so it has to be recognised by its opening words.

**Policy is the caller's.** This module marks and never drops: `classify.py`
deliberately keeps compaction summaries because whether a model rejects them
tests the prompt, while `chat.py` must exclude them. A shared filter would have
taken that choice away silently. So `events()` emits everything it finds,
tagged, and each script decides.

The coordinate system
---------------------

Every record carries `seq`, `turn`, `epoch` and `uuid`. That last one is the
point: a derived view is a *lens*, not a copy, and you can be as aggressive
about truncation as you like when the original is one lookup away. The previous
generation of files carried none of these, so nothing could be joined to
anything and "we can always go back to refined" was a hope rather than a
mechanism.

`epoch` comes from the filename `reduce.py` wrote, because the byte-prefix
property holds only within an epoch and a compaction is where the transcript
and the context permanently diverge — 42,449 tokens became 9,114 in the one
observed case, with 5 of 46 messages preserved.

Usage:
    python3 session.py --list
    python3 session.py --show 2ac71e1f            # the session as a document
    python3 session.py --actions 2ac71e1f         # the action log
    python3 session.py --stats                    # what the corpus contains
"""

import argparse
import collections
import glob
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
sys.path.insert(0, REPO)
sys.path.insert(0, HERE)


def home():
    env = (os.environ.get("CLAUDE_RESYNC_HOME")
           or os.environ.get("CLAUDE_TRANSCRIPTS_HOME"))
    if env:
        return env
    new = os.path.join(os.path.expanduser("~"), ".claude-resync")
    if os.path.isdir(new):
        return new
    legacy = os.path.join(os.path.expanduser("~"), ".claude-transcripts")
    return legacy if os.path.isdir(legacy) else new


REFINED = os.path.join(home(), "refined")

# --------------------------------------------------------------------------
# format facts
# --------------------------------------------------------------------------

# Platform-generated text arriving with role "user". Not a thing anyone typed.
SYS_PREFIX = re.compile(
    r"^\s*<(task-notification|bash-|local-command|system-reminder|command-name)")
INTERRUPT = re.compile(r"^\[Request interrupted")

# A compaction summary is a real user-role line and isMeta does not catch it.
MACHINE_PREFIXES = (
    "this session is being continued from a previous conversation",
    "caveat: the messages below were generated by the user while running",
)

RE_COMMAND_NAME = re.compile(r"^\s*<command-name>\s*/?([\w:.-]+)")
RE_COMMAND_ARGS = re.compile(r"<command-args>(.*?)</command-args>", re.S)
# Same as intercept.py's RE_BACK, so `/ds -3 ...` strips identically and one
# marker is not counted as two.
RE_BACK = re.compile(r"^-?(\d+)$")

# AskUserQuestion returns its answers as prose.
RE_ANSWER_PAIR = re.compile(r'"((?:[^"\\]|\\.)*)"="((?:[^"\\]|\\.)*)"')

# Denial kinds a human is responsible for. permission-rule is a static
# allowlist and automode-* is the harness; counting either as friction reports
# the settings file as a symptom.
USER_DENIALS = ("user-rejected",)

MARKER_COMMANDS = ("ds",)


def is_machine_summary(text):
    low = (text or "")[:120].lower()
    return any(low.startswith(p) for p in MACHINE_PREFIXES)


def slash_command(text):
    """(name, args) for a slash-command line, else (None, None)."""
    m = RE_COMMAND_NAME.match(text or "")
    if not m:
        return None, None
    args = RE_COMMAND_ARGS.search(text or "")
    return m.group(1), (args.group(1).strip() if args else "")


def split_back(raw):
    """`-3 the container path assumption` -> (3, "the container path ...")."""
    raw = (raw or "").strip()
    first, _, rest = raw.partition(" ")
    m = RE_BACK.match(first)
    return (int(m.group(1)), rest.strip()) if m else (0, raw)


def parse_answers(result_text):
    """[(question, answer)] from an AskUserQuestion result's prose."""
    if not isinstance(result_text, str):
        return []
    return [(q.replace('\\"', '"'), a.replace('\\"', '"'))
            for q, a in RE_ANSWER_PAIR.findall(result_text)]


def text_of(message):
    c = (message or {}).get("content")
    if isinstance(c, str):
        return c
    return " ".join(b.get("text", "") for b in (c or [])
                    if isinstance(b, dict) and b.get("type") == "text")


def result_text(block):
    c = block.get("content")
    if isinstance(c, str):
        return c
    return json.dumps(c, ensure_ascii=False, default=str) if c is not None else ""


# --------------------------------------------------------------------------
# tool signatures — the field that makes C2 and C4 deterministic
# --------------------------------------------------------------------------

# Which input field names the thing a tool acted on. Order matters: the first
# present wins.
TARGET_FIELDS = ("file_path", "path", "notebook_path", "command", "url",
                 "pattern", "query", "prompt")

RE_WS = re.compile(r"\s+")


# A heredoc body is the payload, not the action: two `cat <<MSG` writing
# different text are the same action attempted twice, so the body is dropped
# before the signature is taken. Nothing else is dropped.
RE_HEREDOC = re.compile(r"<<-?\s*'?\"?(\w+)'?\"?.*?^\1", re.S | re.M)


def signature(tool, tool_input):
    """A stable, comparable identity for "the same action, tried again".

    C2 is a string equality once this exists, and a judgement call if it does
    not. So the label has to distinguish two different actions — which the
    first version did not.

    It cut the command at the first ` && `, on the theory that the leading
    words identify the attempt. Almost every real command is `cd <somewhere>
    && <the actual work>`, so it kept the `cd` and discarded the work.
    Measured: 950 of 5,537 Bash actions — 17.2% — collapsed to a bare
    `cd <path>`, with one label covering 82 unrelated commands. It made C2
    blind to real repeats and liable to fire on unrelated ones, and it made
    the evidence unreadable: a verdict concluded "no commits are present" when
    all seven entries were `git add ... && git commit ...`.

    Now the whole command is kept, minus heredoc bodies, capped for
    comparability."""
    inp = tool_input or {}
    if tool == "Bash":
        cmd = str(inp.get("command") or "")
        cmd = RE_HEREDOC.sub("<<...", cmd)
        cmd = RE_WS.sub(" ", cmd).strip()
        return "bash:" + cmd[:160]
    for f in TARGET_FIELDS:
        if inp.get(f):
            v = RE_WS.sub(" ", str(inp[f])).strip()
            return "%s:%s" % (tool.lower(), v[:120])
    return (tool or "?").lower()


def target(tool, tool_input):
    """What the action touched, when that is a path or url."""
    inp = tool_input or {}
    for f in ("file_path", "path", "notebook_path", "url"):
        if inp.get(f):
            return str(inp[f])
    return None


# --------------------------------------------------------------------------
# loading
# --------------------------------------------------------------------------

def sessions():
    """Session ids that have a transcript in refined/."""
    out = set()
    for p in glob.glob(os.path.join(REFINED, "*.epoch*.jsonl")):
        out.add(os.path.basename(p).split(".epoch")[0])
    for p in glob.glob(os.path.join(REFINED, "*.inflight.*.jsonl")):
        out.add(os.path.basename(p).split(".inflight")[0])
    return sorted(out)


def resolve(prefix, have=None):
    have = have or sessions()
    hit = [s for s in have if s.startswith(prefix)]
    if len(hit) == 1:
        return hit[0]
    if not hit:
        raise SystemExit("no session matches %r" % prefix)
    raise SystemExit("%r is ambiguous: %s" % (prefix, ", ".join(s[:8] for s in hit)))


def _epoch_of(path):
    m = re.search(r"\.epoch(\d+)\.jsonl$", path)
    return int(m.group(1)) if m else None


def raw_lines(sid):
    """Ordered, deduped transcript rows, each tagged with its epoch.

    Snapshots within an epoch are byte prefixes of each other, so the largest
    file is read first and later duplicates are skipped by uuid. The epoch
    matters because the transcript and the context diverge permanently at a
    compaction, and B3 (post-compaction rework) cannot be seen without it."""
    paths = (glob.glob(os.path.join(REFINED, "%s.epoch*.jsonl" % sid))
             + glob.glob(os.path.join(REFINED, "%s.inflight.*.jsonl" % sid)))
    # Earliest epoch first, largest snapshot first within an epoch. The order
    # matters and sorting by size alone was a bug: epoch1 is usually the larger
    # file, so it was read first, every shared line was tagged epoch 1, and
    # epoch0's lines were then deduped away — leaving every session looking
    # single-epoch and B3 undetectable. A line belongs to the EARLIEST epoch it
    # appears in, because that is when it was written; appearing again in a
    # later snapshot only means it survived. In-flight captures belong to no
    # epoch and are read last.
    def order(p):
        ep = _epoch_of(p)
        return (999 if ep is None else ep, -os.path.getsize(p))

    seen, rows = set(), []
    for p in sorted(paths, key=order):
        ep = _epoch_of(p)
        with open(p, errors="replace") as fh:
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                try:
                    d = json.loads(line)
                except Exception:
                    continue
                key = d.get("uuid") or (d.get("timestamp"), d.get("type"),
                                        str(d.get("content"))[:60])
                if key in seen:
                    continue
                seen.add(key)
                d["_epoch"] = ep
                rows.append(d)
    rows.sort(key=lambda d: d.get("timestamp") or "")
    return rows


# --------------------------------------------------------------------------
# events — everything, tagged; the caller decides what to drop
# --------------------------------------------------------------------------

SPEECH = ("developer", "assistant_text")


def events(sid, rows=None):
    """The session as an ordered list of tagged records.

    Kinds emitted:
      developer       a message the developer typed (`machine` marks a
                      compaction summary, `meta` a platform-generated line)
      assistant_text  one text block — a stated plan, decision or assumption
      tool_use        what the assistant DID: tool, input, signature, target
      tool_result     what it learned: ok / error, text, and the full byte size
      question        an AskUserQuestion, with its outcome and answers
      denial          a tool use refused, with its kind
      marker          a `/ds` note: ground truth, never a trigger

    `turn` counts speaker alternation over SPEECH only, so a tool call belongs
    to the turn that issued it. That is what lets an action be attributed to
    the request that prompted it, which is the whole of A1 and C3."""
    rows = rows if rows is not None else raw_lines(sid)
    out = []
    seq = 0
    turn = -1
    last_speaker = None
    tools = {}            # tool_use_id -> (name, input)
    pending_q = {}        # tool_use_id -> event

    def emit(kind, row, **kw):
        nonlocal seq
        rec = {"seq": seq, "turn": max(turn, 0), "epoch": row.get("_epoch"),
               "uuid": row.get("uuid"), "at": row.get("timestamp"),
               "session": sid, "kind": kind}
        rec.update(kw)
        out.append(rec)
        seq += 1
        return rec

    for d in rows:
        t = d.get("type")

        if t == "assistant":
            if last_speaker != "assistant":
                turn += 1
                last_speaker = "assistant"
            for b in (d.get("message") or {}).get("content") or []:
                if not isinstance(b, dict):
                    continue
                if b.get("type") == "text":
                    txt = (b.get("text") or "").strip()
                    if txt:
                        emit("assistant_text", d, text=txt)
                elif b.get("type") == "tool_use":
                    name, inp = b.get("name"), b.get("input") or {}
                    tools[b.get("id")] = (name, inp)
                    ev = emit("tool_use", d, tool=name, input=inp,
                              tool_use_id=b.get("id"),
                              sig=signature(name, inp),
                              target=target(name, inp))
                    if name == "AskUserQuestion":
                        q = emit("question", d, tool_use_id=b.get("id"),
                                 asked=[x.get("question") for x in
                                        inp.get("questions") or []],
                                 options=[[o.get("label") for o in
                                           x.get("options") or []]
                                          for x in inp.get("questions") or []],
                                 outcome="answered", answers=[])
                        pending_q[b.get("id")] = q
                    del ev
            continue

        if t != "user":
            continue

        content = (d.get("message") or {}).get("content")
        blocks = content if isinstance(content, list) else []

        for b in blocks:
            if not isinstance(b, dict) or b.get("type") != "tool_result":
                continue
            tuid = b.get("tool_use_id")
            name = (tools.get(tuid) or (None, None))[0]
            txt = result_text(b)
            if tuid in pending_q:
                q = pending_q.pop(tuid)
                if d.get("toolDenialKind"):
                    q["outcome"] = ("clarify" if d.get("userFeedback")
                                    else d["toolDenialKind"])
                else:
                    opts = {o for row in q["options"] for o in row if o}
                    for qq, aa in parse_answers(txt):
                        q["answers"].append({
                            "question": qq, "answer": aa,
                            # An answer matching no offered label is the
                            # developer rejecting the frame — invisible in
                            # `outcome`, which reads "answered" either way.
                            "offered": _offered(aa, opts)})
            emit("tool_result", d, tool=name, tool_use_id=tuid,
                 ok=not b.get("is_error"), text=txt, bytes=len(txt))

        kind = d.get("toolDenialKind")
        if kind:
            emit("denial", d, denial_kind=kind, by_user=kind in USER_DENIALS,
                 feedback=d.get("userFeedback") or "")
            continue

        text = (text_of(d.get("message")) or "").strip()

        name, args = slash_command(text)
        if name:
            if name in MARKER_COMMANDS:
                back, note = split_back(args)
                if last_speaker != "developer":
                    turn += 1
                    last_speaker = "developer"
                emit("marker", d, source="/" + name, note=note, back=back)
            continue

        if not text or INTERRUPT.match(text) or SYS_PREFIX.match(text):
            continue

        if last_speaker != "developer":
            turn += 1
            last_speaker = "developer"
        emit("developer", d, text=text, meta=bool(d.get("isMeta")),
             machine=is_machine_summary(text))

    for q in pending_q.values():
        q["outcome"] = "no-result"
    return out


def _norm_label(s):
    return " ".join((s or "").split()).lower().replace("(recommended)", "").strip()


def _offered(answer, labels):
    a = _norm_label(answer)
    if not a or not labels:
        return None
    return any(_norm_label(l) == a for l in labels)


# --------------------------------------------------------------------------
# derived views — the shapes the taxonomy needs
# --------------------------------------------------------------------------

def speech(evs, include_machine=False, include_meta=False):
    """Just what was said. The exchange and claim-pair views start here."""
    out = []
    for e in evs:
        if e["kind"] not in SPEECH:
            continue
        if e["kind"] == "developer":
            if e.get("meta") and not include_meta:
                continue
            if e.get("machine") and not include_machine:
                continue
        out.append(e)
    return out


def actions(evs):
    """The action log: one row per tool call, with its outcome joined on.

    C2 (repeated failing action) and C4 (work undone) come straight out of
    this with no model involved — C2 is a run of equal `sig` values, C4 is a
    write to a target that a later action reverses."""
    res = {}
    for e in evs:
        if e["kind"] == "tool_result":
            res[e.get("tool_use_id")] = e
    out = []
    for e in evs:
        if e["kind"] != "tool_use":
            continue
        r = res.get(e.get("tool_use_id"))
        out.append({"seq": e["seq"], "turn": e["turn"], "at": e["at"],
                    "epoch": e["epoch"], "uuid": e["uuid"],
                    # Carried so a result can be paired to its command exactly.
                    # Dropping it forced consumers to guess by walking back for
                    # the nearest call of the same tool, which mislabelled 430
                    # of 7,693 results — 5.6% — whenever similar calls ran
                    # together. The pairing was always available; it was thrown
                    # away one layer too early.
                    "tool_use_id": e.get("tool_use_id"),
                    "tool": e["tool"], "sig": e["sig"], "target": e["target"],
                    "outcome": ("ok" if r and r["ok"] else
                                "error" if r else "no-result"),
                    "result_bytes": (r or {}).get("bytes", 0),
                    "result_head": ((r or {}).get("text") or "")[:400]})
    return out


def turns(evs, include_machine=False):
    """Contiguous same-speaker speech collapsed into one turn.

    A chat client shows a person's consecutive lines as one message. The
    harness emits assistant narration as separate text blocks — 3702 blocks
    against 527 turns, 7:1 — and treating those as messages shreds one turn
    into seven. Collapsed, the corpus is 527 assistant turns to 528 developer
    turns: a perfectly alternating two-party conversation."""
    out, cur = [], None
    for e in speech(evs, include_machine=include_machine):
        who = "developer" if e["kind"] == "developer" else "assistant"
        if cur and cur["who"] == who:
            cur["events"].append(e)
        else:
            if cur:
                out.append(cur)
            cur = {"who": who, "events": [e], "turn": e["turn"],
                   "at": e["at"], "epoch": e["epoch"]}
    if cur:
        out.append(cur)
    for t in out:
        t["text"] = "\n\n".join(x["text"] for x in t["events"]).strip()
        t["words"] = len(t["text"].split())
        t["seq_from"] = t["events"][0]["seq"]
        t["seq_to"] = t["events"][-1]["seq"]
    return out


def work_after(evs, turn_index):
    """Every action issued in the assistant turn(s) answering a developer turn.

    The join that A1, A3 and C3 need: a request with no matching work is a
    dropped instruction, work with no matching request is scope overrun. Both
    readings need actions attributed to the turn that prompted them, which is
    what `turn` on every record is for."""
    return [a for a in actions(evs) if a["turn"] == turn_index + 1]


def evidence_before(evs, seq):
    """Tool results the assistant had seen before making a claim at `seq`.

    B1 (acted on an unverified premise) is "was there any" and D2 (asserted a
    state its own tool output contradicts) is "does the claim agree with
    them"."""
    out = []
    for e in evs:
        if e["seq"] >= seq:
            break
        if e["kind"] == "tool_result":
            out.append(e)
        elif e["kind"] == "assistant_text":
            out = []        # only since the previous claim
    return out


def epochs(evs):
    """{epoch: (first seq, last seq)} — the spans B3 needs."""
    out = {}
    for e in evs:
        ep = e.get("epoch")
        if ep is None:
            continue
        lo, hi = out.get(ep, (e["seq"], e["seq"]))
        out[ep] = (min(lo, e["seq"]), max(hi, e["seq"]))
    return out


# --------------------------------------------------------------------------
# CLI — for looking, not for pipelines
# --------------------------------------------------------------------------

def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--list", action="store_true")
    ap.add_argument("--show", metavar="SESSION")
    ap.add_argument("--actions", metavar="SESSION")
    ap.add_argument("--stats", action="store_true")
    args = ap.parse_args(argv)

    if args.list:
        for s in sessions():
            print(s)
        return 0

    if args.show:
        sid = resolve(args.show)
        for t in turns(events(sid)):
            print("%s  turn %-3d %-9s %4d words  %s"
                  % ((t["at"] or "")[11:19], t["turn"], t["who"], t["words"],
                     " ".join(t["text"].split())[:96]))
        return 0

    if args.actions:
        sid = resolve(args.actions)
        for a in actions(events(sid)):
            print("%-5d turn %-3d %-6s %-9s %s"
                  % (a["seq"], a["turn"], a["outcome"],
                     "%dB" % a["result_bytes"], a["sig"][:80]))
        return 0

    if args.stats:
        k = collections.Counter()
        tools = collections.Counter()
        n = 0
        for sid in sessions():
            evs = events(sid)
            n += 1
            for e in evs:
                k[e["kind"]] += 1
                if e["kind"] == "tool_use":
                    tools[e["tool"]] += 1
        print("%d session(s)" % n)
        for kind, c in k.most_common():
            print("   %-15s %6d" % (kind, c))
        print("\ntop tools: %s" % dict(tools.most_common(8)))
        return 0

    ap.print_help()
    return 2


if __name__ == "__main__":
    sys.exit(main())
